# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodTeest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodTeest

  pod 'CAHelpView', :git => 'https://bilalm211@bitbucket.org/contentarcadeios/cahelpview.git'
  
  #pod 'CAHelpView', :path => '/Users/bilalmustafa/Documents/Libraries/cahelpview'

end
